### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by dper1629** [gabireze/tiktok-all-liked-videos-remover#2]
Everytime I try to use the extension nothing happens and an message pops up in the console.
https://imgur.com/a/veHb3XJ

**Comment by gabireze** [comment]
Hi good evening, thank you for the feedback. I've looked into your case and the extension still works with my Chrome. You need to access your profile on TikTok (for example, https://www.tiktok.com/@USERNAME) and then click on the extension and the start button for the extension process to begin.

The extension will automatically navigate to the liked videos tab, click on the first video, and begin to unlike the video, move to the next, unlike, etc.

Sometimes messages do appear in the browser console, but they are not directly related to the extension, but rather errors that the TikTok site itself shows.

I tested it here, and in 5 minutes, it removed 100 videos.

I recommend following the process I described below to update the browser extensions and the browser itself.

If it does not work, you can install the extension on the Edge browser, which will also work. Edge is already present on Windows operating systems. I say this because some users also couldn't get it to work on Google Chrome but it worked perfectly on Edge. I am still investigating why this might happen, I think it might be because of browser version differences.

Thank you again for the feedback.

1. Access chrome://settings/ to go to Chrome's settings.
2. Click on the "About Chrome" option in the left side menu.
3. In this section, you can check if the browser is updated. If it is not updated, update it and then close and reopen the browser.

![Captura de tela 2024-04-07 184035](https://github.com/gabireze/tiktok-all-liked-videos-remover/assets/31194373/ebf8afc0-0356-4ec7-8069-d38876b0bb99)

4. Access the URL chrome://extensions/ to display all the extensions you have installed in Chrome.
5. Click on "Developer Mode" and activate this option.

![Captura de tela 2024-04-07 184003](https://github.com/gabireze/tiktok-all-liked-videos-remover/assets/31194373/546644e5-ad50-479d-b917-35dbc6ef9d9b)

6. Click on "Update" to update all the extensions.
7. Ensure that the extensions have been updated when this pop-up is shown.

![Captura de tela 2024-04-07 184010](https://github.com/gabireze/tiktok-all-liked-videos-remover/assets/31194373/ef245b6c-b824-426b-af51-24a1003021fa)

![Captura de tela 2024-04-07 184015](https://github.com/gabireze/tiktok-all-liked-videos-remover/assets/31194373/2fa5e842-fae1-44f9-a615-e5be5239ce6e)

**Comment by gabireze** [comment]
Hi @dper1629 ,

Thank you for bringing this issue to my attention.

As it has been over a month since this issue was opened and there have been no further updates, I will be closing this issue for now. If you still encounter any problems or have any additional information, please feel free to comment here, and I will be happy to reopen the issue and assist you further.

Thank you for your understanding and cooperation.

Best regards.

**Comment by gabireze** [comment]
Just adding an update for anyone reading this issue later.

Since late 2025 / early 2026, TikTok Web has been showing **inconsistent behavior** for actions like unliking, unfavoriting, and unreposting videos. In some cases, the UI interaction happens, the network request returns a success response, and no visible error appears in the console, **but the action is not actually persisted on TikTok’s backend**.

Because of that:

* The extension may appear to run correctly.
* Console warnings or errors may show up, but they are usually generated by TikTok itself.
* The liked/favorited/reposted videos may still appear when checking the account again, especially on the mobile app.

This behavior is **platform-side** and affects a subset of users. Unfortunately, a browser extension cannot reliably work around this, since the limitation happens after TikTok accepts the request.

At the moment, the **TikTok mobile app remains the only fully reliable way** to manage likes, favorites, and reposts.

Leaving this issue closed, but documenting the current limitation here for transparency.

**Comment by gabireze** [comment]
Hi everyone! Just a quick update: I’ve released version 2.0 of the extension, which changes the way removals work.

The old version simulated UI clicks on each TikTok video, and TikTok was increasingly blocking or rate-limiting those actions. In v2.0 the extension now uses the same authenticated web APIs that TikTok itself uses to list and remove your liked/reposted videos, and the actual removal runs in the page context so it behaves like a normal site action. In practice this has stopped the issue where likes/reposts “pretended” to be removed but stayed on the account.

If you were having problems before, please update to the latest version from the Chrome Web Store and try again:

- TikTok All Reposted Videos Remover: https://chromewebstore.google.com/detail/tiktok-all-reposted-video/amgpfdpibiacligkkkbeonfhmonkgjhg
- TikTok All Liked Videos Remover: https://chromewebstore.google.com/detail/tiktok-all-liked-videos-r/eafmacjdgennnmhagdkdckgjokmnllci

If the problem persists after updating to v2.0, feel free to comment here with details (browser, country/region, and a short description of what you see) so I can investigate further.
