### ISSUE TITLE
Delete All reposts

### ISSUE THREAD

**Issue by Silverhorse7** [gabireze/tiktok-all-liked-videos-remover#3]
Can we have an extra feature to delete all reposts?

Thanks in advance for your effort and tool.

**Comment by gabireze** [comment]
Hi @Silverhorse7,

I’ve created a Chrome extension that does exactly what you’re asking for! It’s called TikTok All Reposted Videos Remover, and you can check it out on the Chrome Web Store [here](https://chromewebstore.google.com/detail/tiktok-all-reposted-video/amgpfdpibiacligkkkbeonfhmonkgjhg).

You can also find the GitHub repository for the project [here](https://github.com/gabireze/tiktok-all-reposted-videos-remover).

Feel free to try it out and let me know if you have any feedback or suggestions.

Thanks!

**Comment by gabireze** [comment]
Just adding an update here for anyone finding this issue later.

The repost-removal extension still exists and works **when TikTok Web properly persists the action**. However, since late 2025 / early 2026, TikTok Web has shown **inconsistent behavior** where repost, like, and favorite actions may return a success response but are **not actually saved on TikTok’s backend**.

In those cases:

* The extension behaves correctly.
* TikTok Web reports success.
* But reposts may still appear when checking the account on the mobile app.

This is a platform-side limitation affecting a subset of users and is outside the control of any browser extension. At the moment, the **TikTok mobile app remains the only fully reliable way** to remove reposts.

Leaving this issue closed, but documenting the current limitation for transparency.

Thanks to everyone who has used the tool and shared feedback.

**Comment by gabireze** [comment]
Hi everyone! Just a quick update: I’ve released version 2.0 of the extension, which changes the way removals work.

The old version simulated UI clicks on each TikTok video, and TikTok was increasingly blocking or rate-limiting those actions. In v2.0 the extension now uses the same authenticated web APIs that TikTok itself uses to list and remove your liked/reposted videos, and the actual removal runs in the page context so it behaves like a normal site action. In practice this has stopped the issue where likes/reposts “pretended” to be removed but stayed on the account.

If you were having problems before, please update to the latest version from the Chrome Web Store and try again:

- TikTok All Reposted Videos Remover: https://chromewebstore.google.com/detail/tiktok-all-reposted-video/amgpfdpibiacligkkkbeonfhmonkgjhg
- TikTok All Liked Videos Remover: https://chromewebstore.google.com/detail/tiktok-all-liked-videos-r/eafmacjdgennnmhagdkdckgjokmnllci

If the problem persists after updating to v2.0, feel free to comment here with details (browser, country/region, and a short description of what you see) so I can investigate further.
